create_project vp "/Users/tmarhguy/logisim_evolution_workspace/alu_top/main/sandbox//vp"
set_property part xc7a35tftg256-1 [current_project]
set_property target_language VHDL [current_project]
add_files "/Users/tmarhguy/logisim_evolution_workspace/alu_top/main/verilog/gates/XOR_GATE_BUS_ONEHOT.v"
add_files "/Users/tmarhguy/logisim_evolution_workspace/alu_top/main/verilog/gates/AND_GATE.v"
add_files "/Users/tmarhguy/logisim_evolution_workspace/alu_top/main/verilog/gates/NOR_GATE_8_INPUTS.v"
add_files "/Users/tmarhguy/logisim_evolution_workspace/alu_top/main/verilog/gates/AND_GATE_4_INPUTS.v"
add_files "/Users/tmarhguy/logisim_evolution_workspace/alu_top/main/verilog/gates/AND_GATE_3_INPUTS.v"
add_files "/Users/tmarhguy/logisim_evolution_workspace/alu_top/main/verilog/gates/NAND_GATE_BUS.v"
add_files "/Users/tmarhguy/logisim_evolution_workspace/alu_top/main/verilog/gates/NOR_GATE_BUS.v"
add_files "/Users/tmarhguy/logisim_evolution_workspace/alu_top/main/verilog/gates/OR_GATE.v"
add_files "/Users/tmarhguy/logisim_evolution_workspace/alu_top/main/verilog/gates/NOR_GATE.v"
add_files "/Users/tmarhguy/logisim_evolution_workspace/alu_top/main/verilog/memory/LogisimCounter.v"
add_files "/Users/tmarhguy/logisim_evolution_workspace/alu_top/main/verilog/plexers/Multiplexer_bus_4.v"
add_files "/Users/tmarhguy/logisim_evolution_workspace/alu_top/main/verilog/plexers/Multiplexer_bus_2.v"
add_files "/Users/tmarhguy/logisim_evolution_workspace/alu_top/main/verilog/plexers/Multiplexer_bus_8.v"
add_files "/Users/tmarhguy/logisim_evolution_workspace/alu_top/main/verilog/circuit/main.v"
add_files "/Users/tmarhguy/logisim_evolution_workspace/alu_top/main/verilog/arith/Adder.v"
add_files "/Users/tmarhguy/logisim_evolution_workspace/alu_top/main/verilog/toplevel/logisimTopLevelShell.v"
add_files "/Users/tmarhguy/logisim_evolution_workspace/alu_top/main/verilog/base/synthesizedClockGenerator.v"
add_files "/Users/tmarhguy/logisim_evolution_workspace/alu_top/main/verilog/base/logisimTickGenerator.v"
add_files "/Users/tmarhguy/logisim_evolution_workspace/alu_top/main/verilog/base/LogisimClockComponent.v"
add_files -fileset constrs_1 "/Users/tmarhguy/logisim_evolution_workspace/alu_top/main/xdc/vivadoConstraints.xdc"
exit
